/*
 *   Copyright (c) 2024 Arcology Network

 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.

 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.

 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package common

// This function determines the type of path, either ACL or ETH based on the key.
// It helps determine the proper path codec to use. Paths generated by the EVM have
// a fixed length prefix of 32 bytes, but the ACL paths are variable length. So we need to know
// which codec to use to encode & decode the data associated with the path.
func GetPathType(key string) uint8 {
	if len(key) >= ETH10_STORAGE_NATIVE_PREFIX_LENGTH {
		k := key[ETH10_STORAGE_PREFIX_LENGTH:ETH10_STORAGE_NATIVE_PREFIX_LENGTH]
		if k == "/native/" {
			return ETH_PATH_TYPE
		}
	}
	return ACL_PATH_TYPE
}
